# Generated by Django 3.2.9 on 2022-04-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_berita_editor'),
        ('home', '0002_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
