# Generated by Django 3.2.9 on 2022-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_berita_editor'),
        ('home', '0003_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editor',
        ),
    ]
