# Generated by Django 3.2.9 on 2022-04-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi_topik', models.TextField()),
                ('tanggal_upload', models.DateField()),
                ('gambar', models.ImageField(upload_to='')),
                ('kategori', models.CharField(choices=[('UMKM', 'UMKM'), ('Berita', 'Berita'), ('Forum', 'Forum'), ('Rekomendasi', 'Rekomendasi'), ('Aplikasi', 'Aplikasi'), ('Serba Serbi Ramadhan', 'Serba Serbi Ramadhan'), ('Modal UMKM', 'Modal UMKM')], max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_upload', models.DateField()),
                ('isi_komentar', models.TextField()),
                ('id_topik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topik')),
                ('username_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
