# Generated by Django 3.2.9 on 2022-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='')),
                ('isi_berita', models.TextField()),
            ],
        ),
    ]
