# Generated by Django 3.2.9 on 2022-03-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('judul', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=100)),
                ('gambar', models.ImageField(max_length=255, upload_to='')),
                ('isi_berita', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.admin')),
            ],
        ),
    ]
