# Generated by Django 3.2.9 on 2022-04-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_editor'),
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.editor'),
        ),
    ]
