# Generated by Django 3.2.9 on 2022-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_berita_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='editor',
            field=models.CharField(max_length=100),
        ),
    ]
