# Generated by Django 3.2.9 on 2022-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_berita_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(upload_to='static/berita/%Y/%m/%d'),
        ),
    ]
