# Generated by Django 3.2.9 on 2022-04-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_alter_berita_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
